app/utils/countrycodes.py
Based on ExpDev07/coronavirus-tracker-api#56, I created a new synonym for countrycode `DE`
=> Add synonyms for Germany

README.md, app/coordinates.py, app/location.py, app/routes/v2/locations.py, app/timeline.py
Add option to include timelines when accessing ``/v2/locations``.
Include timelines by adding ``?timelines=true`` query parameter to your request.
=> Timelines option

app/utils/countrycodes.py
This time it's a bit more.
Also, now we have a problem with the initial choice I made for the `default_code`. We should do something about it the near future, that means before somebody gets sick somewhere there in the disputed territories.
=> Countries and aliases

README.md
Of course the API is made in Python but we also need a way to easily access it without having to worry about what request to send. The added repo is a wrapper that does just that.
=> Added Wrapper for Python

README.md
I added a C# wrapper for the API, and it'll soon be available as a nuget package
=> Added C# Wrapper

README.md, app/location/__init__.py, app/services/location/jhu.py, tests/test_location.py, tests/test_routes.py
Add ``last_updated`` (UTC ISO) to ``Location``s as discussed in https://github.com/ExpDev07/coronavirus-tracker-api/issues/77.
=> added last_updated to Location

app/services/location/jhu.py, tests/test_routes.py
Due to how JHU has restructured their files, indexes have messed up in regards to recovery numbers, leading to countries pointing to wrong data. This drops support for recovery numbers for JHU source completely and it will display 0.
Related: https://github.com/ExpDev07/coronavirus-tracker-api/pull/156.
=> hotfix for location mismatch data

README.md
The information about where to retrieve the ids for locations was added to the table of path parameters.
Please review. 
Thanks :)
=> Where to find locations ids added to docs

README.md
Hi,
Thanks for this API.
I added another C# wrapper for the API, and the nuget package is already available here [https://www.nuget.org/packages/Covid19Tracker.NET/](https://www.nuget.org/packages/Covid19Tracker.NET/).
This wrapper contains methods that return objects, which can be easily handled in applications. The await/async best practices are also used.
=> Added another C# wrapper(Covid19Tracker.NET)

app/router/locations.py, tests/test_routes.py
=> No locations data 404

Makefile, app/__init__.py, app/config/settings.py, app/coordinates.py, app/data/__init__.py, app/location/__init__.py, app/location/csbs.py, app/main.py, app/router/__init__.py, app/router/v1/__init__.py, app/router/v1/all.py, app/router/v1/confirmed.py, app/router/v1/deaths.py, app/router/v1/recovered.py, app/router/v2/__init__.py, app/router/v2/latest.py, app/router/v2/locations.py, app/router/v2/sources.py, app/services/location/__init__.py, app/services/location/csbs.py, app/services/location/jhu.py, app/timeline.py, app/utils/countries.py, app/utils/date.py, app/utils/populations.py, pylintrc, tests/test_countries.py
* address outstanding linting warning with fixes or error suppression
* re-enable lint CI stage
=> Address Linting warnings

README.md
Hi great work putting this API together! :)
I've added another C# client for consuming the APIs based on the latest v2 contracts with support for all data types that should make it easier for any C# developers (.NET standard / core / framework) to use the API.
=> Adding another C# client for the APIs

.dockerignore, Dockerfile, docker-compose.yml
* Adds Dockerfile for image build.
* Adds dockercompose to facilitate workflow.
* Adds dockerignore for futures adjusts.
* Adds "--host" parameter on uvicorn to fix networking problem when run inside container. 
Notes:
The pipenv is slow down the image build, also, increase ~37mb of image's size but this pull request is just to add docker flow for development enviroment. To run on production enviroments safety, we will need to do somes ajusts that could change the project a little bit. 
The app waits a environment variable called "PORT" but, even without it, i can run the api using the port 8000 (a little bit strange). 
#252
=> Add docker compatibility

Dockerfile, README.md, docker-compose.yml, tasks.py
Our current dockerfile was using the [tiangolo/uvicorn-gunicorn-fastapi
](https://fastapi.tiangolo.com/deployment/#tiangolouvicorn-gunicorn-fastapi) docker image, but was configured to run as `uvicorn` directly.
* Updated Dockerfile and docker-compose to work with `gunicorn` (running `uvicorn` workers).
* Publish the correct port (`80`)
* Added `invoke docker --build` to easily build a docker image.
* Added `invoke docker --run` to start the container and "publish" the correct port
fixes #269 
After building and running the container, the API should be reachable locally at
http://192.168.99.100/
=> Fix Docker ports & Gunicorn

README.md
Previously stated NYT provides timeseries for US states and counties which could be misleading since this API currently supports county level.
=> Update README to clarify NYT data

README.md, uvicorn.Dockerfile
Single instance Uvicorn based Dockerfile.
In many cases a full Gunicorn deployment with multiple workers is overkill.
=> Uvicorn based Docker

app/__init__.py, app/main.py
=> add GZIP support for responses > 1000bytes

app/services/location/csbs.py, app/services/location/jhu.py, app/services/location/nyt.py
add info level logs for various steps when retrieving source data.
My hunch is that this may be where we run into problems.
=> add minimal logging for location services

Procfile, app/services/location/jhu.py, app/utils/countries.py
* Set gunicorn to always use 4 workers
* log the process id when refreshing jhu data
* move missing country code log to `debug` level
=> Gunicorn with 4 workers

app/services/location/jhu.py, app/services/location/nyt.py
I believe the cache size can be much lower still. 
AFIAK the `maxsize` isn't the "size" of the cache so much as it is the number of recent calls to the function to save. `get_category()` only has 3 possible parameters it receives. So my understanding is as long as the max size is greater than those 3 different function calls everything should work fine.
As per the standard lib `lru` cache which I believe `cachetools` is based on.
https://docs.python.org/3/library/functools.html#functools.lru_cache
>Decorator to wrap a function with a memoizing callable that saves up to the maxsize most recent calls.
* investigate and further optimize the cache settings to reduce memory usage
=> reduce TTL cache maxsize

Pipfile, Pipfile.lock, app/config.py, app/main.py, app/services/location/jhu.py, app/services/location/nyt.py, requirements-dev.txt, requirements.txt
Support Scout APM
https://scoutapm.com/
=> Scout APM Monitoring

app/routers/v2.py, app/services/location/csbs.py, app/services/location/jhu.py, app/services/location/nyt.py
Fixes https://github.com/ExpDev07/coronavirus-tracker-api/issues/489
=> Handle indexes differing for locations between the JHU timeseries
